/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hd_ndklearn_FirstNdkClass */

#ifndef _Included_com_hd_ndklearn_FirstNdkClass
#define _Included_com_hd_ndklearn_FirstNdkClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hd_ndklearn_FirstNdkClass
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hd_ndklearn_FirstNdkClass_getCLanguageString
  (JNIEnv *, jobject);

/*
 * Class:     com_hd_ndklearn_FirstNdkClass
 * Method:    addAandB
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_hd_ndklearn_FirstNdkClass_addAandB
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_hd_ndklearn_FirstNdkClass
 * Method:    mulAandB
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_com_hd_ndklearn_FirstNdkClass_mulAandB
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
